"""One-shot read-only audit: find SqlCache parquets whose column shape
contradicts the SELECT-list of their sibling .sql file.

Failure mode being detected: the snapshot harness's `run_query_data`
wraps `_method` returns of type list/dict/Series into
`pd.DataFrame({"value": result})` and the writethrough path then writes
that wrapped DataFrame back into the SqlCache under the **inner**
method's SQL hash. The cache thereby holds a 1-column shape for an SQL
that selects 3+ columns. Any live caller that invokes the original
method afterward gets the wrong shape from cache and crashes.

Walks every <hash>.parquet/.sql pair under tests/query_snapshots/*_cache/
and reports any whose parquet column count differs substantially from
the SELECT-list count parsed naively from the .sql header.
"""
from __future__ import annotations

import re
from pathlib import Path

import pandas as pd


SNAPSHOTS_ROOT = Path(__file__).parent / "query_snapshots"


def _count_select_columns(sql: str) -> int | None:
    """Crude parse of the top-level SELECT list. Returns column count, or
    None if the SQL doesn't look like a SELECT we can analyze.

    Counts top-level commas (depth 0) between SELECT and the matching FROM.
    Good enough for the snapshot caches we see — the SQL is generated by
    SQLAlchemy and uses a stable shape."""
    sql = sql.strip()
    m = re.match(r"(?is)^\s*SELECT\s+(?:DISTINCT\s+)?(.*?)\s+FROM\s+", sql)
    if not m:
        return None
    select_list = m.group(1)
    depth = 0
    cols = 1
    for c in select_list:
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        elif c == "," and depth == 0:
            cols += 1
    return cols


def audit_cache_dir(cache_dir: Path) -> list[tuple[Path, int, int, list[str]]]:
    """Return [(parquet_path, sql_cols, parquet_cols, parquet_col_names)] for mismatches."""
    mismatches: list[tuple[Path, int, int, list[str]]] = []
    for parquet_path in sorted(cache_dir.glob("*.parquet")):
        sql_path = parquet_path.with_suffix(".sql")
        if not sql_path.exists():
            continue
        try:
            sql_text = sql_path.read_text()
        except OSError:
            continue
        sql_cols = _count_select_columns(sql_text)
        if sql_cols is None:
            continue  # not a SELECT we can analyze
        try:
            df_cols = list(pd.read_parquet(parquet_path).columns)
        except Exception:
            continue
        if len(df_cols) >= sql_cols:
            continue
        mismatches.append((parquet_path, sql_cols, len(df_cols), df_cols))
    return mismatches


def main() -> None:
    any_mismatch = False
    for cache_dir in sorted(SNAPSHOTS_ROOT.glob("*_cache")):
        if not cache_dir.is_dir():
            continue
        mismatches = audit_cache_dir(cache_dir)
        if not mismatches:
            print(f"{cache_dir.name}: clean")
            continue
        any_mismatch = True
        print(f"{cache_dir.name}: {len(mismatches)} mismatch(es)")
        for parquet_path, sql_cols, df_cols, df_col_names in mismatches:
            print(
                f"  {parquet_path.name}: SQL selects {sql_cols} cols, "
                f"parquet has {df_cols} ({df_col_names})"
            )
    if any_mismatch:
        print("\nMismatches indicate cache poisoning by the wrap-then-writeback path.")
        print("After landing the cache-poisoning fix, delete each mismatched parquet/.sql/.json")
        print("triple and re-run pytest to repopulate from bsq.execute().")


if __name__ == "__main__":
    main()
