SELECT ts_b.comstock_building_type, sum(1) / CAST(35040 AS DECIMAL) AS sample_count, sum(baseline.weight / CAST(35040 AS REAL)) AS units_count, sum(CASE WHEN (ts_u.bldg_id IS NULL) THEN ts_b."out.electricity.total.energy_consumption" ELSE ts_u."out.electricity.total.energy_consumption" END * baseline.weight) AS "electricity.total.energy_consumption", sum(CASE WHEN (ts_u.bldg_id IS NULL) THEN ts_b."out.natural_gas.total.energy_consumption" ELSE ts_u."out.natural_gas.total.energy_consumption" END * baseline.weight) AS "natural_gas.total.energy_consumption" 
FROM (SELECT comstock_amy2018_r2_2025_ts_by_state.bldg_id AS bldg_id, comstock_amy2018_r2_2025_ts_by_state.state AS state, comstock_amy2018_r2_2025_ts_by_state.timestamp AS timestamp, baseline."in.comstock_building_type" AS comstock_building_type, comstock_amy2018_r2_2025_ts_by_state."out.electricity.total.energy_consumption" AS "out.electricity.total.energy_consumption", comstock_amy2018_r2_2025_ts_by_state."out.natural_gas.total.energy_consumption" AS "out.natural_gas.total.energy_consumption" 
FROM comstock_amy2018_r2_2025_ts_by_state JOIN (SELECT * 
FROM comstock_amy2018_r2_2025_md_by_state_and_county_parquet 
WHERE CAST(comstock_amy2018_r2_2025_md_by_state_and_county_parquet.upgrade AS VARCHAR) = '0') AS baseline ON baseline.bldg_id = comstock_amy2018_r2_2025_ts_by_state.bldg_id AND baseline.state = comstock_amy2018_r2_2025_ts_by_state.state AND baseline.state = 'CO' 
WHERE CAST(comstock_amy2018_r2_2025_ts_by_state.upgrade AS VARCHAR) = '0' AND comstock_amy2018_r2_2025_ts_by_state.state = 'CO') AS ts_b LEFT OUTER JOIN (SELECT comstock_amy2018_r2_2025_ts_by_state.bldg_id AS bldg_id, comstock_amy2018_r2_2025_ts_by_state.state AS state, comstock_amy2018_r2_2025_ts_by_state.timestamp AS timestamp, baseline."in.comstock_building_type" AS comstock_building_type, comstock_amy2018_r2_2025_ts_by_state."out.electricity.total.energy_consumption" AS "out.electricity.total.energy_consumption", comstock_amy2018_r2_2025_ts_by_state."out.natural_gas.total.energy_consumption" AS "out.natural_gas.total.energy_consumption" 
FROM comstock_amy2018_r2_2025_ts_by_state JOIN (SELECT * 
FROM comstock_amy2018_r2_2025_md_by_state_and_county_parquet 
WHERE CAST(comstock_amy2018_r2_2025_md_by_state_and_county_parquet.upgrade AS VARCHAR) = '0') AS baseline ON baseline.bldg_id = comstock_amy2018_r2_2025_ts_by_state.bldg_id AND baseline.state = comstock_amy2018_r2_2025_ts_by_state.state AND baseline.state = 'CO' 
WHERE CAST(comstock_amy2018_r2_2025_ts_by_state.upgrade AS VARCHAR) = '1' AND comstock_amy2018_r2_2025_ts_by_state.state = 'CO') AS ts_u ON ts_b.bldg_id = ts_u.bldg_id AND ts_b.state = ts_u.state AND ts_b.timestamp = ts_u.timestamp JOIN (SELECT * 
FROM comstock_amy2018_r2_2025_md_by_state_and_county_parquet 
WHERE CAST(comstock_amy2018_r2_2025_md_by_state_and_county_parquet.upgrade AS VARCHAR) = '0') AS baseline ON baseline.bldg_id = ts_b.bldg_id AND baseline.state = ts_b.state AND baseline.state = 'CO' 
WHERE baseline.state = 'CO' GROUP BY 1 ORDER BY 1