SELECT date_trunc('month', date_add('second', -900, ts_b.timestamp)) AS timestamp, count(DISTINCT (baseline.bldg_id, baseline."in.nhgis_tract_gisjoin", baseline.state)) AS sample_count, (count(DISTINCT (baseline.bldg_id, baseline."in.nhgis_tract_gisjoin", baseline.state)) * sum(baseline.weight)) / CAST(sum(1) AS DECIMAL) AS units_count, sum(1) / CAST(count(DISTINCT (baseline.bldg_id, baseline."in.nhgis_tract_gisjoin", baseline.state)) AS DECIMAL) AS rows_per_sample, sum(ts_b."out.electricity.total.energy_consumption" * baseline.weight) AS "electricity.total.energy_consumption__baseline", sum(ts_u."out.electricity.total.energy_consumption" * baseline.weight) AS "electricity.total.energy_consumption__upgrade", sum((coalesce(ts_b."out.electricity.total.energy_consumption", 0) - coalesce(ts_u."out.electricity.total.energy_consumption", 0)) * baseline.weight) AS "electricity.total.energy_consumption__savings" 
FROM (SELECT comstock_amy2018_r2_2025_ts_by_state.bldg_id AS bldg_id, comstock_amy2018_r2_2025_ts_by_state.state AS state, comstock_amy2018_r2_2025_ts_by_state.timestamp AS timestamp, comstock_amy2018_r2_2025_ts_by_state."out.electricity.total.energy_consumption" AS "out.electricity.total.energy_consumption" 
FROM comstock_amy2018_r2_2025_ts_by_state JOIN (SELECT * 
FROM comstock_amy2018_r2_2025_md_by_state_and_county_parquet 
WHERE CAST(comstock_amy2018_r2_2025_md_by_state_and_county_parquet.upgrade AS VARCHAR) = '0') AS baseline ON baseline.bldg_id = comstock_amy2018_r2_2025_ts_by_state.bldg_id AND baseline.state = comstock_amy2018_r2_2025_ts_by_state.state AND baseline.state = 'CO' 
WHERE CAST(comstock_amy2018_r2_2025_ts_by_state.upgrade AS VARCHAR) = '0' AND comstock_amy2018_r2_2025_ts_by_state.state = 'CO') AS ts_b JOIN (SELECT comstock_amy2018_r2_2025_ts_by_state.bldg_id AS bldg_id, comstock_amy2018_r2_2025_ts_by_state.state AS state, comstock_amy2018_r2_2025_ts_by_state.timestamp AS timestamp, comstock_amy2018_r2_2025_ts_by_state."out.electricity.total.energy_consumption" AS "out.electricity.total.energy_consumption" 
FROM comstock_amy2018_r2_2025_ts_by_state JOIN (SELECT * 
FROM comstock_amy2018_r2_2025_md_by_state_and_county_parquet 
WHERE CAST(comstock_amy2018_r2_2025_md_by_state_and_county_parquet.upgrade AS VARCHAR) = '0') AS baseline ON baseline.bldg_id = comstock_amy2018_r2_2025_ts_by_state.bldg_id AND baseline.state = comstock_amy2018_r2_2025_ts_by_state.state AND baseline.state = 'CO' 
WHERE CAST(comstock_amy2018_r2_2025_ts_by_state.upgrade AS VARCHAR) = '1' AND comstock_amy2018_r2_2025_ts_by_state.state = 'CO') AS ts_u ON ts_b.bldg_id = ts_u.bldg_id AND ts_b.state = ts_u.state AND ts_b.timestamp = ts_u.timestamp JOIN (SELECT * 
FROM comstock_amy2018_r2_2025_md_by_state_and_county_parquet 
WHERE CAST(comstock_amy2018_r2_2025_md_by_state_and_county_parquet.upgrade AS VARCHAR) = '0') AS baseline ON baseline.bldg_id = ts_b.bldg_id AND baseline.state = ts_b.state AND baseline.state = 'CO' 
WHERE baseline.state = 'CO' GROUP BY 1 ORDER BY 1